FROM python:3.10

RUN pip install --upgrade pip

RUN pip install pandas
RUN pip install pandas-profiling
RUN pip install numpy==1.23
RUN pip install scipy
RUN pip install matplotlib
RUN pip install seaborn
RUN pip install jupyter
RUN pip install category_encoders

RUN pip install mglearn
RUN pip install imageio
RUN pip install pydotplus
RUN pip install dtreeviz
RUN pip install graphviz

RUN pip install scikit-learn==1.1.3
RUN pip install xgboost
RUN pip install lightgbm

